#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing reboot listener...\n"
sudo cp listen-for-reboot.py /usr/local/bin/
sudo chmod +x /usr/local/bin/listen-for-reboot.py

echo "=> Starting reboot listener...\n"
sudo cp listen-for-reboot.sh /etc/init.d/
sudo chmod +x /etc/init.d/listen-for-reboot.sh

sudo update-rc.d listen-for-reboot.sh defaults
sudo /etc/init.d/listen-for-reboot.sh start

echo "Reboot listener installed.\n"
