#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping reboot listener...\n"
sudo update-rc.d listen-for-reboot.sh remove
sudo /etc/init.d/listen-for-reboot.sh stop

echo "=> Removing reboot listener...\n"
sudo rm -rf /usr/local/bin/listen-for-reboot.py 
sudo rm -rf /etc/init.d/listen-for-reboot.sh 

echo "Reboot listener uninstalled.\n"
